[project]
name = "google-antigtravite"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "sathish.k", email = "sathishkishore3848@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "fastapi[standard]>=0.141.1",
    "uvicorn>=0.54.0",
]

[project.scripts]
google-antigtravite = "google_antigtravite:main"

[build-system]
requires = ["uv_build>=0.12.11,<0.13.0"]
build-backend = "uv_build"

[tool.uv.workspace]
members = [
    "annual-report-qa",
]
